In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
            [[10,11,12],
             [13,14,15],
             [16,17,18]]])


In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [14]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

##  2.Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 4, 4, 6, 0],
       [9, 4, 5, 8, 9],
       [0, 8, 2, 7, 0]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.57821486, 0.18698972, 0.29497061],
       [0.43980269, 0.73510611, 0.269577  ],
       [0.75017554, 0.37894648, 0.41822284],
       [0.35361561, 0.36192756, 0.70826877],
       [0.90163034, 0.32432277, 0.63145586]])

In [29]:
random_array_2.shape

(5, 3)

In [ ]:
# Pseudo-random numbers
np.random.seed()